GENERIC_SERVER: generic_server Class Reference
generic_server Class Reference
This is a singleton class and provides framework functionality.
#include <generic_server.h>
Public Member Functions
int init ()
int log (unsigned int, unsigned int, char *)
enables logging to framework managed log file.
int log (unsigned int, unsigned int, string)
enables logging to framework managed log file.
int get_log_size (void)
int rollover_logs (void)
Rolls over log files, configured in Master configuation file.
int close_log (void)
int sock_init (void)
Really useful only for Windows, just invokes WSAStartup API.
int swap_bytes (unsigned char *key)
A simple utility to swap upper / lower 8 bytes of a 16 bytes buffer.
int bb_getline (char *sav_buffer, size_t length, size_t conn_s)
int bb_getline (char *sav_buffer, size_t length, size_t conn_s, int)
int get_status (unsigned char *buff)
string get_cur_time (void)
string trim (const std::string &)
int socket_close (SOCKET)
int close_thread_ids (void)
SOCKET create_socket (int)
bool get_verify_client (void)
int set_verify_client (bool)
int check_enabled_plugin (string)
int check_allocated_port (string in_plugin_id, string in_plugin_port)
int set_conf_file (char *cfile)
int set_process_name (char *cfile)
int reload_conf_file (void)
int get_command_port (void)
int plugin_read_conf_file (GENERIC_PLUGIN *, int thread_no)
int syslog_msg (unsigned int debug_level, unsigned int verbose_level, string data)
string get_framework_version (void)
int print_key_message ()
int get_thread_id ()
int rel_thread_id (int)
bool check_plugin_aliases (vector< string > &alias)
int set_plugins_path (vector< string > &plugin_parms)
string get_plugins_path ()
int setnonblocking (SOCKET)
int setblocking (SOCKET)
int get_thread_sync_mutex (void)
int rel_thread_sync_mutex (void)
int ssl_async_write (SSL *ssl, char *buf, int size)
int ssl_async_read (SSL *ssl, char *buf, int size)
int ssl_async_accept (SSL *ssl)
vector< string > split (const string &s, const string &delim, const bool keep_empty)
GENERIC_PLUGIN * load_shared_lib (string library_image, string)
int unload_shared_lib (string plugin_type)
vector< GENERIC_PLUGIN * >
::iterator get_start_iterator (void)
vector< GENERIC_PLUGIN * >
::iterator get_end_iterator (void)
Static Public Member Functions
static generic_server * instance (void)
Instantiate tis singleton class only once and return pointer to instantiated object later on..
Public Attributes
vector< GENERIC_PLUGIN * >
::iterator itr
vector< GENERIC_PLUGIN * > v
Vector to hold all plug-ins.
unsigned int timeout_seconds
int max_threads
int command_port
ofstream log_file
string logname
map< string, void * > dll_handles
map< int, THREAD_INFO > thread_ids
Map to store all currently running threads.
map< string, create_fp > factory
Map that has function pointers to 'create_instance()' factory method for all plug-in libraries.
SSLServer sslserver
bool syslog_flag
map< string, bool > bootstrap_jobs
string server_cert
TLS certificate stuff.
string rsa_private_key
string ca_certificate
Static Public Attributes
static generic_server * pinstance = 0
Pointer to singleton framework instance.
Private Member Functions
int get_log_file_mutex (void)
int rel_log_file_mutex (void)
int get_server_params (string, int)
int tls_setup (void)
Initializes TLS.
int remove_devices (map< string, int > &new_ports)
This is invoked when any plug-in entry gets removed from Master configuration file and framework gets signaled.
int remove_all_aliases ()
GENERIC_PLUGIN * initialize_plugin_object (vector< string > plugin_parms, GENERIC_PLUGIN *plugin)
int tls_initialize ()
Validates generic_server framework and CA certificates, calls tls_setup().
int set_access_control (char daemon_flag)
Private Attributes
unsigned int iResult
unsigned int tls_setup_reqd
string conf_file
string process_name
string plugins_path
pthread_mutex_t log_file_mutex
pthread_mutex_t thread_cnt_mutex
pthread_mutex_t thread_sync_mutex
unsigned long max_log_size
int max_logs_saved
bool verify_client
Detailed Description
This is a singleton class and provides framework functionality.
Definition at line 83 of file generic_server.h.
Member Function Documentation
int generic_server::bb_getline (char * sav_buffer, size_t length, size_t conn_s)
Asynchronous socket read utility.
Parameters
[out] sav_buffer Buffer to store read data.
[in] length Maximum number of bytes to read from socket.
Returns
Number of bytes actually read, or zero on error. failure to read any data.
Definition at line 904 of file generic_server.cpp.
 {
         fd_set socks;
         struct timeval timeout;
         char str[MAX_SZ];
         size_t readsock,t;
         size_t bytes_recvd;
     memset(sav_buffer,0,sizeof(sav_buffer));
     memset(str,0,MAX_SZ);
     bytes_recvd = 0;
     while(1)
     {
        FD_ZERO(&socks);
        FD_SET(conn_s,&socks);
        timeout.tv_sec = 0;
        timeout.tv_usec = 50000;
        readsock = select((int)conn_s+1,&socks,NULL,NULL,&timeout);
        if(bytes_recvd && readsock <= 0)
              return(bytes_recvd);
        if(FD_ISSET(conn_s,&socks))
        {
            if ((t = recv(conn_s,str,sizeof(str), 0)) > 0)
            {
                                 memcpy(sav_buffer+bytes_recvd,str,t);
                 bytes_recvd += t;
                 if(bytes_recvd >= length)
                         return(bytes_recvd);
            }
            else
                    {
                return(bytes_recvd);
                    }
        }
     }
 }
bool generic_server::check_plugin_aliases (vector< string > & alias)
Checks for 'alias' plug-ins. An 'alias' is any plug-in that uses the same TCP port of primary plug-in. Framework would use one TCP port/socket to service all 'aliased' plug-ins.
Parameters
[in] &alias Reference to alias Vector within every
Definition at line 290 of file generic_server.cpp.
 {
         ostringstream oss;
     vector <GENERIC_PLUGIN *>::iterator it;
     for(it = get_start_iterator(); it != get_end_iterator();it++)
     {
         if( (*it)->get_plugin_name()    != plugin_parms.at(PLUGIN_NAME)       &&
             (*it)->get_plugin()      == plugin_parms.at(PLUGIN_TYPE)          &&
             (*it)->get_plugin_path() == plugin_parms.at(SHARED_LIB_PATH)      &&
                     (*it)->get_port()        == atoi(plugin_parms.at(PORT).c_str())   &&
                     (*it)->get_conf_file()   == plugin_parms.at(PLUGIN_CONF)          &&
                     (*it)->get_tls_flag()    == atoi(plugin_parms.at(TLS_FLAG).c_str())
                 )
                 {
                         if(!(*it)->find_plugin_alias(plugin_parms.at(PLUGIN_NAME)))
                                         (*it)->add_plugin_alias(plugin_parms.at(PLUGIN_NAME));
             return(true);
                 }
                 else
         if( (*it)->get_plugin_name()    != plugin_parms.at(PLUGIN_NAME)       &&
             (*it)->get_plugin()      == plugin_parms.at(PLUGIN_TYPE)          &&
                     (*it)->get_port()        == atoi(plugin_parms.at(PORT).c_str())   &&
                     (*it)->get_tls_flag()    == atoi(plugin_parms.at(TLS_FLAG).c_str())
                 )
                 {
                         if( (*it)->get_conf_file() != plugin_parms.at(PLUGIN_CONF) ||
                             (*it)->get_plugin_path() != plugin_parms.at(SHARED_LIB_PATH) )
{
                                 oss << " Ignoring attempted plugin alias for: " << (*it)->get_plugin_name() << ". check alias configuration.";
                                 log(LOG_LOW,LOG_LOW,oss.str());
                 return(true);
                         }
                 }
     }
     return(false);
 }
SOCKET generic_server::create_socket (int port)
Creates a 'listen'ing socket for every plugin, sets socket to 'nonblocking' mode.
Parameters
[in] port TCP port for socket to bind.
Returns
socket descriptor on success or zero on error.
Definition at line 1244 of file generic_server.cpp.
Referenced by process_data().
 {
     SOCKET ListenSocket;
     struct addrinfo *result = NULL;
     struct sockaddr_in local_address;
     struct addrinfo hints;
     ostringstream os;
     int iResult;
         os << port;
     memset(&local_address,0,sizeof(local_address));
     memset(&hints, 0,sizeof(hints));
     hints.ai_family = AF_INET;
     hints.ai_socktype = SOCK_STREAM;
     hints.ai_protocol = IPPROTO_TCP;
     hints.ai_flags = AI_PASSIVE;
     iResult = getaddrinfo(NULL, os.str().c_str(), &hints, &result);
     if (iResult != 0)
     {
         os.str("");
         os.clear();
         os  << " Thr.ID:MAIN getaddrinfo failed.";
         log(LOG_LOW,LOG_LOW,os.str());
     }
     ListenSocket = socket(result->ai_family, result->ai_socktype, result->ai_protocol);
     if (ListenSocket == INVALID_SOCKET)
     {
         os.str("");
         os.clear();
         os  << " Thr.ID:MAIN socket creation failed.";
         log(LOG_LOW,LOG_LOW,os.str());
         freeaddrinfo(result);
         return 0;
     }
     local_address.sin_family = AF_INET;
     local_address.sin_addr.s_addr = inet_addr("127.0.0.1");
     local_address.sin_port = htons(port);
     iResult = bind(ListenSocket, (sockaddr *) &local_address, (int)result->ai_addrlen);
     if (iResult != 0)
     {
         os.str("");
         os.clear();
         os  << " Thr.ID:MAIN socket bind failed for port: " << port;
         log(LOG_LOW,LOG_LOW,os.str());
         freeaddrinfo(result);
         shutdown(ListenSocket,2);
 #ifdef WINDOWS
         closesocket(ListenSocket);
 #else
         close(ListenSocket);
 #endif
         return 0;
     }
     iResult = listen(ListenSocket, SOMAXCONN);
     if (iResult == SOCKET_ERROR)
     {
         os.str("");
         os.clear();
         os  << " Thr.ID:MAIN socket listen failed for port: " << port;
         log(LOG_LOW,LOG_LOW,os.str());
         shutdown(ListenSocket,2);
 #ifdef WINDOWS
         closesocket(ListenSocket);
 #else
         close(ListenSocket);
 #endif
         return 0;
     }
         setnonblocking(ListenSocket);
     return(ListenSocket);
 }
int generic_server::init ()
Reads master configuration file, loads plug-in shared libraries and initializes master Vector to store plug-ins.
Definition at line 472 of file generic_server.cpp.
 {
         int ret;
         GENERIC_PLUGIN *plugin;
         vector<string> plugin_parms;
         string line,delim,library_image;
         ostringstream os;
         ret = 0;
 #ifdef WINDOWS
         if (!sock_init())
         {
                 cout << "Can't init socket library! " << endl;
         return(0);
         }
         TCHAR filebuf[MAX_SZ];
         get_exe_directory(filebuf,MAX_SZ);
         SetCurrentDirectory(filebuf);
 #endif
         tls_setup_reqd = 0;
         delim = "|";
         ifstream inf(conf_file.c_str());
     if(!inf)
     {
         cout << " Can't Open file: " << conf_file << endl;
         return(0);
     }
     while(getline(inf, line))
     {
                 line = trim(line);
         if(line.length() == 0 || line.at(0) == '#')
             continue;
                 if(!get_server_params(line,INIT))
                         continue;
                 plugin_parms = split(line,delim,true);
                 if(plugin_parms.size() != 7)
                         continue;
                 set_plugins_path(plugin_parms);
                 // returns true if PLUGIN_NAME is a new alias or an existing alias
                 // generic_plugin will be updated in case of new alias
                 if(check_plugin_aliases(plugin_parms))
                         continue;
                 plugin = load_shared_lib(plugin_parms.at(SHARED_LIB_PATH),plugin_parms.at(PLUGIN_TYPE));
                 if(plugin == NULL)
                 {
                         os  << " Thr.ID:MAIN load_library failed: " << plugin_parms.at(SHARED_LIB_PATH) << " PLUGIN_TYPE: " << plugin_parms.at(PLUGIN_TYPE) << endl;
                         log(LOG_LOW,LOG_LOW,os.str());
                 return 0;
                 }
                 plugin = initialize_plugin_object(plugin_parms,plugin);
                 if(plugin == NULL)
                 return(0);
                 v.push_back(plugin);
     }
         inf.close();
         if(!tls_initialize())
                 return(0);
 return(1);
 }
GENERIC_PLUGIN * generic_server::initialize_plugin_object (vector< string > plugin_parms, GENERIC_PLUGIN * plugin) private
Update plug-in object with plug-in specific configuration parameters from plug-in conf file.
Parameters
[in] plugin_parms Vector that holds plug-in configuration details.
[in] plugin Plug-in object to be updated.
Returns
Updated plugin object or NULL on error.
Definition at line 1138 of file generic_server.cpp.
References generic_plugin::bootstrap_init(), generic_plugin::bootstrap_name(), generic_plugin::initialize_socket(), generic_plugin::pinstance, and generic_plugin::server_init().
 {
         int ret;
         ostringstream os;
         SOCKET ListenSocket;
         string bootstrap_name;;
         plugin->set_port(atoi(plugin_parms.at(PORT).c_str()));
         plugin->set_plugin(plugin_parms.at(PLUGIN_TYPE));
         plugin->set_plugin_name(plugin_parms.at(PLUGIN_NAME));
         plugin->set_plugin_number(plugin_parms.at(PLUGIN_NUMBER));
         plugin->set_plugin_path(plugin_parms.at(SHARED_LIB_PATH));
         plugin->set_tls_flag(atoi(plugin_parms.at(TLS_FLAG).c_str()));
         memcpy(&plugin->pinstance,&pinstance,4);
         if( (ListenSocket = plugin->initialize_socket(plugin_parms.at(PORT))) == 0)
                 return(NULL);
         plugin->set_socket(ListenSocket);
         if(plugin->get_tls_flag())
                 tls_setup_reqd = 1;
         if(plugin_parms.size() > PLUGIN_CONF)
         {
                 plugin->set_conf_file(plugin_parms.at(PLUGIN_CONF));
                 ret = plugin_read_conf_file(plugin,0);
         if(!ret)         // read in plugin_specific config parameters
         {
             os  << " Thr.ID:MAIN plugin_init failed for: " << plugin->get_plugin_name() << endl;
             log(LOG_LOW,LOG_LOW,os.str());
             return(NULL);
                 }
         }
         bootstrap_name = plugin->bootstrap_name();
         map<string,bool>::iterator it = bootstrap_jobs.find(bootstrap_name);
         if(it == bootstrap_jobs.end() && bootstrap_name != "")
         {
                 os  << " Thr.ID:MAIN Invoking bootstrap: " << bootstrap_name << " on plug-in: " << plugin->get_plugin_name();
                 log(LOG_LOW,LOG_LOW,os.str());
                 os.str("");
                 os.clear();
                 if(!plugin->bootstrap_init(bootstrap_name))
                 {
                         os  << " Thr.ID:MAIN failed to bootstrap: " << bootstrap_name << " on plug-in: " << plugin->get_plugin_name();
             log(LOG_LOW,LOG_LOW,os.str());
             return(NULL);
                 }
                 bootstrap_jobs[bootstrap_name] = true;
                 os  << " Thr.ID:MAIN Successfully bootstrapped: " <<  bootstrap_name << " on plug-in: " << plugin->get_plugin_name();
                 log(LOG_LOW,LOG_LOW,os.str());
                 os.str("");
                 os.clear();
         }
         if(!check_enabled_plugin(plugin_parms.at(PLUGIN_TYPE)))
         {
                 if(!plugin->server_init()) // Will do only once per plugin type
                 {
                         os  << " Thr.ID:MAIN thread. server_init failed for: " << plugin_parms.at(PLUGIN_TYPE) << endl;
                         log(LOG_LOW,LOG_LOW,os.str());
                         return(NULL);
                 }
         }
         setnonblocking(ListenSocket);
         return(plugin);
 }
GENERIC_PLUGIN * generic_server::load_shared_lib (string library_image, string plugin_type)
Dynamically loads plug-in shared library.
Parameters
[in] library_image Path to shared library image.
[in] plugin_type PLUGIN_TYPE to load.
Returns
function pointer to 'create_instance()' factory method of loaded plug-in. NULL on error.
Definition at line 599 of file generic_server.cpp.
 {
         GENERIC_PLUGIN *plugin_p;
         ostringstream os;
 #ifndef WINDOWS
         void* handle = dlopen(library_image.c_str(),RTLD_LAZY);
         if(handle == NULL)
         {
         os  << " Thr.ID:MAIN Can't load DLL: " << " " <<  dlerror();
         log(LOG_LOW,LOG_LOW,os.str());
                 return(NULL);
         }
         factory[plugin_type] = (create_fp) dlsym(handle, "create_instance");
         dll_handles[plugin_type] =  (void *) handle;
 #else
         HMODULE handle;
         handle = LoadLibrary(library_image.c_str());
         if(handle == NULL)
         {
                 os.str("");
         os.clear();
         os  << " Thr.ID:MAIN Error loading: " << library_image << " " << GetLastError();
         log(LOG_LOW,LOG_LOW,os.str());
                 return(NULL);
         }
         factory[plugin_type] = (create_fp) GetProcAddress(handle, "create_instance");
         dll_handles[plugin_type] = (void *) handle;
 #endif
         if(factory[plugin_type] == NULL)
         {
         os  << " Thr.ID:MAIN Can't instantiate PLUGIN_TYPE: " << plugin_type;
         log(LOG_LOW,LOG_LOW,os.str());
                 return(NULL);
         }
         plugin_p = (factory[plugin_type])();
     os  << " Thr.ID:MAIN loaded plugin version: " << plugin_p->get_plugin_version() << " for PLUGIN_TYPE: " << plugin_type;
     log(LOG_LOW,LOG_LOW,os.str());
         return(plugin_p);
 }
The documentation for this class was generated from the following files:
framework/generic_server.h
framework/generic_server.cpp