GENERIC_SERVER: framework/control.h File Reference
control.h File Reference
Master program that initiates GENERIC_SERVER, spawns a thread for each plug-in and runs message loop for that plug-in.
#include <map>
#include <vector>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <pthread.h>
#include "sslserver.h"
Macros
#define TLS_REQ 1
#define SOCKET_REQ 2
#define PR_SET_NAME 15
Functions
void sig_int (int sig_num)
void do_nothing (int sig_num)
void * thread_fn (void *inp_arg)
void * ssl_thread_fn (void *inp_arg)
void daemonize ()
unsigned int get_data_size (unsigned char *recvbuf)
int add_size (unsigned char *recvbuf, unsigned int size)
string get_input_plugin_name (char *buffer)
static int process_client_req (SOCKET clnt_sock, int plugin_init_state, GENERIC_PLUGIN *plugin_p, int thread_no, generic_server *framework)
static int process_ssl_client_req (SOCKET clnt_sock, SSL *ssl, int plugin_init_state, GENERIC_PLUGIN *plugin_p, int thread_no, generic_server *framework)
static int terminate_client_session (SOCKET clnt_sock, generic_server *framework, GENERIC_PLUGIN *plugin_p, int thread_no, unsigned char *senduf)
static int terminate_ssl_client_session (SSL *ssl, generic_server *framework, GENERIC_PLUGIN *plugin_p, int thread_no, unsigned char *senduf)
static int print_source_hostname (int clnt_sock, int req_type, generic_server *framework, int thread_no, GENERIC_PLUGIN *plugin_p)
static int process_data (void)
Main loop to 'select()' sockets from multiple clients.
static unsigned int init_sock_fds (fd_set *, SOCKET)
static int chk_command_sock (fd_set *, SOCKET)
static int launch_thread (GENERIC_PLUGIN *generic_plugin, unsigned int new_slot)
static int chk_all_clients (fd_set *socks)
static int read_socket (unsigned char *buffer, SOCKET sock, int size)
Detailed Description
Master program that initiates GENERIC_SERVER, spawns a thread for each plug-in and runs message loop for that plug-in.
Author
Suraj Vijayan
Date
: 2013/07/01 14:16:20
Contact: suraj.nosp@m.@bro.nosp@m.adcom.nosp@m..com
Definition in file control.h.
Function Documentation
static int launch_thread (GENERIC_PLUGIN * generic_plugin, unsigned int new_slot) static
Launches a new thread to run a plug-in. Thread could be for an TLS session or a non-TLS session.
Parameters
[in] plugin_p Pointer to generic_plugin object
[in] new_slot slot position into thread_ids map
Returns
1 always
Definition at line 689 of file control.cpp.
References generic_server::pinstance, and generic_server::thread_ids.
 {
     generic_server *fwork = generic_server::pinstance;
 #ifdef LINUX
         pthread_attr_t attr; // thread attribute
                                                  // set thread detachstate attribute to DETACHED
     fwork->get_thread_sync_mutex();
     pthread_attr_init(&attr);
     pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
 #endif
     if(generic_plugin->get_tls_flag())
     {
 #ifdef WINDOWS
         fwork->get_thread_sync_mutex();
                 fwork->thread_ids[new_slot].th = (HANDLE)_beginthreadex(NULL, 0, &ssl_thread_fn, (void *)generic_plugin, 0, NULL );
 #else
         pthread_create(&fwork->thread_ids[new_slot].th,&attr,ssl_thread_fn, (void *)generic_plugin);
 #endif
     }
     else
     {
 #ifdef WINDOWS
         fwork->get_thread_sync_mutex();
                 fwork->thread_ids[new_slot].th = (HANDLE)_beginthreadex(NULL, 0, &thread_fn, (void *)generic_plugin, 0, NULL );
 #else
         pthread_create(&fwork->thread_ids[new_slot].th,&attr,thread_fn, (void *)generic_plugin);
 #endif
     }
 #ifdef LINUX
     pthread_attr_destroy(&attr);
 #endif
     fwork->close_thread_ids();
     return(1);
 }
static int process_client_req (SOCKET clnt_sock, int plugin_init_state, GENERIC_PLUGIN * plugin_p, int thread_no, generic_server * framework) static
This function gets called in a plug-in specific thread to process request sent by client on raw (non TLS) session. Once a valid request is received, 'process_request()' method on plug-in is invoked. Message structure:
SIGNATURE - 4 bytes SIGNATURE for all messages
PAYLOAD_SIZE - 4 bytes network byte order
DATA - PAYLOAD_SIZE data
Data payload could be:
PLUGIN_NAME_LEN - 4 bytes network byte order
PLUGIN_NAME - Size as defined by <PLUGIN_NAME_LEN>
APPLICATION_DATA - PAYLOAD_SIZE-(4+PLUGIN_NAME_LEN)
Parameters
[in] clnt_sock Client socket to read/write
[in] plugin_init_state Flag to indicate return status of plugin_init() callback
[in] plugin_p Pointer to plug-in object
[in] thread_no Thread number assigned by framework
[in] framework Pointer to framework object
Returns
1 on success, 0 on failure
static int process_ssl_client_req (SOCKET clnt_sock, SSL * ssl, int plugin_init_state, GENERIC_PLUGIN * plugin_p, int thread_no, generic_server * framework) static
This function gets called in a plug-in specific thread to process request sent by client on TLS enabled session. Once a valid request is received, 'process_request()' method on plug-in is invoked. Message structure:
SIGNATURE - 4 bytes SIGNATURE for all messages
PAYLOAD_SIZE - 4 bytes network byte order
DATA - PAYLOAD_SIZE data
Data payload could be:
PLUGIN_NAME_LEN - 4 bytes network byte order
PLUGIN_NAME - Size as defined by <PLUGIN_NAME_LEN>
APPLICATION_DATA - PAYLOAD_SIZE-(4+PLUGIN_NAME_LEN)
Parameters
[in] clnt_sock Client socket attached to SSL
[in] ssl Pointer to SSL structure
[in] plugin_init_state Flag to indicate return status of plugin_init() callback
[in] thread_no Thread number assigned by framework
[in] framework Pointer to framework object
Returns
1 on success, 0 on failure
static int terminate_client_session (SOCKET clnt_sock, generic_server * framework, GENERIC_PLUGIN * plugin_p, int thread_no, unsigned char * senduf) static
This function gets called in a plug-in specific thread whenever a non-TLS client session is to be terminated.
Parameters
[in] clnt_socket Client socket to read/write
[in] framework Pointer to framework object
[in] plugin_p Pointer to plugin object
[in] thread_no Thread number assigned by framework
[in] sendbuf NULL terminated ASCII data to send to client
Returns
1 always
Definition at line 416 of file control.cpp.
References generic_server::log(), and generic_plugin::shutdown_plugin().
 {
     int len;
     ostringstream os;
     len = strlen((char *)sendbuf);
     send(clnt_sock, (char *)sendbuf, (int)len, 0 );
     plugin_p->shutdown_plugin(); // Aborting SESSION..
     os.str("");
     os.clear();
     os  << " Thr.ID:" << thread_no << " Plugin:" << plugin_p->get_plugin_name() << " Quitting thread." << sendbuf;
     fwork->log(LOG_LOW,LOG_LOW,os.str());
         fwork->socket_close(clnt_sock);
     delete plugin_p;
     fwork->rel_thread_id(thread_no);
     return(1);
 }
static int terminate_ssl_client_session (SSL * ssl, generic_server * framework, GENERIC_PLUGIN * plugin_p, int thread_no, unsigned char * senduf) static
This function gets called in a plug-in specific thread whenever a TLS client session is to be terminated.
Parameters
[in] ssl Pointer to SSL structure
[in] framework Pointer to framework object
[in] plugin_p Pointer to plugin object
[in] thread_no Thread number assigned by framework
[in] sendbuf NULL terminated ASCII data to send to client
Returns
1 always
Definition at line 435 of file control.cpp.
References generic_server::log(), and generic_plugin::shutdown_plugin().
 {
         int len,ssl_response,status;
         ostringstream os;
         char buf[100];
     len = strlen((char *)sendbuf);
         status = recv(SSL_get_fd(ssl), (char*) buf, 10, MSG_PEEK);
     if(status > 0)
         {
                 ssl_response = fwork->ssl_async_write((SSL *)ssl,  (char *)sendbuf, (int)len);
                 if(ssl_response > 0)
                 {
                         while((SSL_shutdown(ssl)) == 0)
                         ;
                 }
         }
     plugin_p->shutdown_plugin();
     os  << " Thr.ID:" << thread_no << " ChipID:" << plugin_p->get_plugin_name() << " Quitting thread." << sendbuf;
     fwork->log(LOG_LOW,LOG_LOW,os.str());
         fwork->socket_close(SSL_get_fd(ssl));
         SSL_free((SSL *)ssl);
         ERR_free_strings();
         ERR_remove_state(0);
     delete plugin_p;
     fwork->rel_thread_id(thread_no);
     return(1);
 }